#!/usr/bin/env bash

set -Ceu

readonly NORMAL="$(tput sgr0)"
readonly RED="$(tput setaf 1)"
readonly GREEN="$(tput setaf 2)"
readonly YELLOW="$(tput setaf 3)"

# For debugging
function debug() {
    if [[ $DEBUG ]]; then
        echo ">>> $*"
    fi
}

# Colorize output to RED color
function red_log() {
    echo -e "${RED}$*${NORMAL}"
}

# Colorize output to GREEN color
function green_log() {
    echo -e "${GREEN}$*${NORMAL}"
}

# Colorize output to YELLOW color
function yellow_log() {
    echo -e "${YELLOW}$*${NORMAL}"
}

# Check the command exists
function has() {
    type "$1" >/dev/null 2>&1
}

# Suspends the processing
function pause() {
    read -rs -p "$(green_log "Press any key to continue...")" -n 1
    echo ""
}

# Ask user, yes or no
# Usage: if ask; then echo "Yes"; else echo "No"; fi
function ask() {
    local -r prompt_message="Are you sure to continue? (y/n): "

    local answer
    while true; do
        read -rp "$(green_log "${prompt_message}")" answer
        case "${answer}" in
        [yY])
            return 0
            ;;
        [nN])
            return 1
            ;;
        esac
    done
}

# Update packages
# Note that this function is only executable for ubuntu only
function update_package() {
    if [[ "$(uname)" = 'Linux' ]]; then

        if has "apt-fast"; then
            green_log "Updating packages using \`apt-fast\`..."
            sudo apt-fast update -y && sudo apt-fast full-upgrade -y
        elif has "apt-get"; then
            green_log "Updating packages using \`apt-get\`..."
            sudo apt-get update -y && sudo apt-get full-upgrade -y
        else
            red_log "Cannot update package, because \`apt-get\` or \`apt-fast\` command was not available."
            exit 0
        fi

        local last_executed_ret_val
        last_executed_ret_val=$?
        if [[ $last_executed_ret_val ]]; then
            green_log "Package updated successfully!"
        else
            red_log "Package update failed!"
        fi
    fi
}
